### ISSUE TITLE
App Icon

### ISSUE THREAD

**Issue by meeDamian** [meeDamian/Basic-Info#13]
Prepare any App Icon

**Comment by meeDamian** [comment]
Maybe sth really basic like the "info" icon in a primary/accent app color:

<img width="378" alt="screen shot 2015-12-30 at 21 01 44" src="https://cloud.githubusercontent.com/assets/526657/12051035/987e491c-af38-11e5-8282-9851d590672b.png">

cc What's your opinion @Rasmuhamed ?

**Comment by AleksanderSleszynski** [comment]
@chester1000 I choose the "info outline" icon.
