### ISSUE TITLE
Create a proper "no location permission granted" notification.

### ISSUE THREAD

**Issue by meeDamian** [meeDamian/Basic-Info#25]
Just fill in stuff here: [GeoChecker.java#L98-L106](https://github.com/chester1000/Basic-Info/blob/3cbe40ac700eca6114edad35881ca4acc5fc2582/app/src/main/java/com/example/julian/locationservice/GeoChecker.java#L98-L106)

**Comment by AleksanderSleszynski** [comment]
A comment about this , I am not sure if such a thing you wanted to achieve.
